name: android

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Build AAB with Gradle
      # We build an AAB as well for uploading to the the Play Store.
      run: cd android; ./gradlew bundlerelease
    - name: Build APKs with Gradle
      # "assemblerelease" is very fast after "bundlerelease".
      run: cd android; ./gradlew assemblerelease
    - name: Save AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minetest-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
    - name: Save APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
